include:
  - board: corneish_zen_v2_left
    shield: nice_view_adapter nice_view
  - board: corneish_zen_v2_right
    shield: nice_view_adapter nice_view
  - board: nice_nano_v2
    shield: settings_reset
